### ISSUE TITLE
Does backup and restore require login?

### ISSUE THREAD

**Issue by Weav3r** [JICA98/DailyAL#29]
First, I'd like to say thanks for this app. It is awesome in both UI,UX and functionality.

**Problem:**
Currently using the app anonymously since I don't have a MAL account and don't want to create one just yet. I do however, have a few anime bookmarked which I'd like to backup and restore but upon granting storage permission and attempting the backup it still doesn't work.

**Diagnostic info**
Android 10
Version: DailyAL 2024.8.3+95
Permission granted: Yes

**Comment by JICA98** [comment]
@Weav3r Thanks for reporting this and its great that you are liking the app.
While creating the backup, did you get a notification saying that the backup is saved in downloads folder?
It might be also be an android issue because I haven't tested it on this version.
![Screenshot_20240924-182945_DailyAL](https://github.com/user-attachments/assets/105ba7c3-2be3-4c94-8725-e6effc04a72d)

**Comment by JICA98** [comment]
To comment on the actual question:
No, backup/restore doesn't require login.

**Comment by Weav3r** [comment]
> While creating the backup, did you get a notification saying that the backup is saved in downloads folder?

I did the very first time I tried it but there was nothing saved in my Downloads directory. After the very first attempt I never saw that confirmation toast again. I tried disabling and enabling the storage permissions multiple times but it still didn't work. 

 > It might be also be an android issue because I haven't tested it on this version.
 
 Probably. I'll try installing an older version as well to check
